---
- name: Install Kitty (terminal emulator)
  become: true
  pacman:
    name: kitty
    state: latest
- name: Install Viu (simple terminal image viewer)
  become: true
  pacman:
    name: viu
    state: latest
- name: Setup Kitty
  synchronize:
    delete: true
    src: kitty
    dest: "/$HOME/.config"
