[editor]
mouse = false
middle-click-paste = false
line-number = "relative"
cursorline = false
cursorcolumn = false
completion-replace = true
true-color = true
undercurl = true
bufferline = "always"
color-modes = true
popup-border = "popup"

[editor.auto-pairs]
"(" = ")"
"{" = "}"
"[" = "]"
" = "
"`" = "`"
"<" = ">"

[keys.normal]
esc = [ "collapse_selection", "keep_primary_selection" ]

[keys.normal."C-g"]
"g" = [ ":new", ":insert-output lazygit", ":buffer-close!", ":redraw" ]
"d" = [ ":new", ":insert-output lazydocker", ":buffer-close!", ":redraw" ]
