---
- name: Install Docker Language Server
  kewlfft.aur.aur:
    name: dockerfile-language-server
    state: latest

- name: Install VSCode Language Server Extracted
  kewlfft.aur.aur:
    name: vscode-langservers-extracted
    state: latest

- name: Synchronize the configuration
  synchronize:
    src: helix
    dest: "$HOME/.config"
