---
- name: Install Deno
  pacman:
    name: deno
    state: latest

- name: Clone the repository
  ansible.builtin.git:
    repo: https://github.com/aminnairi/markdown-table-align
    dest: /$HOME/Documents/git/github.com/aminnairi/markdown-table-align/
  register: git_clone_result

- name: Compile the binary
  ansible.builtin.command:
    chdir: /$HOME/Documents/git/github.com/aminnairi/markdown-table-align/
    cmd: deno compile --allow-read --output $HOME/.local/bin/markdown-table-align index.ts
  when: git_clone_result.changed
