# Enable picom
picom &

# Enable background
feh --bg-fill $HOME/.local/share/backgrounds/background.jpg

# Enable natural scrolling on the touchpad
xinput set-prop 9 298 1 

# Enable middle button emulation on the touchpad
xinput set-prop 9 308 1

# Enable two-fingers click
xinput set-prop 9 306 0 1

# Start i3 window manager
exec i3
