# Enable flameshot
flameshot &

# Enable background
feh --bg-fill $HOME/.local/share/backgrounds/background.jpg

# Enable natural scrolling on the touchpad
xinput set-prop "QXTP7868:00 27C6:01E8 Touchpad" "libinput Natural Scrolling Enabled" 1 

# Enable middle button emulation on the touchpad
xinput set-prop "QXTP7868:00 27C6:01E8 Touchpad" "libinput Middle Emulation Enabled" 1

# Enable two-fingers click
xinput set-prop "QXTP7868:00 27C6:01E8 Touchpad" "libinput Click Method Enabled" 0 1

# Set the compose key
# setxkbmap -option compose:ralt

# Start i3 window manager
exec i3
