---
- name: Install Node.js
  become: true
  pacman:
    name: nodejs
    state: latest
- name: Install NPM
  become: true
  pacman:
    name: npm
    state: latest
- name: Install Slidev globally through NPM
  community.general.npm:
    path: /$HOME/.local/lib/node_modules
    name: '@slidev/cli'
    version: 0.47.5
- name: Install Slidev default theme globally through NPM
  community.general.npm:
    path: /$HOME/.local/lib/node_modules
    name: '@slidev/theme-default'
    version: 0.25.0
- name: Install Playwright Chromium for Slidev globally through NPM
  community.general.npm:
    path: /$HOME/.local/lib/node_modules
    name: playwright-chromium
    version: 1.41.2
