# Abbreviations for "docker compose"
abbr --add dcpb "docker compose text build"
abbr --add dcpcf "docker compose config"
abbr --add dcpcp "docker compose cp"
abbr --add dcpce "docker compose create"
abbr --add dcpdn "docker compose down --remove-orphans --volumes --timeout 0"
abbr --add dcpevt "docker compose events"
abbr --add dcpex "docker compose exec"
abbr --add dcpimg "docker compose images"
abbr --add dcpkl "docker compose kill"
abbr --add dcplg "docker compose logs"
abbr --add dcpls "docker compose ls"
abbr --add dcppa "docker compose pause"
abbr --add dcppr "docker compose port"
abbr --add dcppl "docker compose pull"
abbr --add dcpps "docker compose ps"
abbr --add dcprs "docker compose restart"
abbr --add dcprn "docker compose run"
abbr --add dcpsc "docker compose scale"
abbr --add dcpst "docker compose start"
abbr --add dcpsp "docker compose stop"
abbr --add dcpt "docker compose top"
abbr --add dcpups "docker compose unpause"
abbr --add dcpup "docker compose up"
abbr --add dcpv "docker compose version"
abbr --add dcpwt "docker compose wait"
abbr --add dcpwt "docker compose watch"

# Abbrevations for "docker"
abbr --add dca "docker container attach"
abbr --add dccm "docker container commit"
abbr --add dccp "docker container cp"
abbr --add dccr "docker container create"
abbr --add dcdf "docker container diff"
abbr --add dcep "docker container export"
abbr --add dcex "docker container exec"
abbr --add dcisp "docker container inspect"
abbr --add dckl "docker container kill"
abbr --add dclg "docker container logs"
abbr --add dcls "docker container ls"
abbr --add dcpa "docker container pause"
abbr --add dcprn "docker container prune"
abbr --add dcprt "docker container port"
abbr --add dcrm "docker container rm"
abbr --add dcrn "docker container run"
abbr --add dcrnm "docker container rename"
abbr --add dcrs "docker container restart"
abbr --add dcs "docker container stop"
abbr --add dcstr "docker container start"
abbr --add dcsts "docker container stats"
abbr --add dct "docker container top"
abbr --add dcud "docker container update"
abbr --add dcup "docker container unpause"
abbr --add dcw "docker container wait"

# Abbrevations for "docker system"
abbr --add dstdf "docker system df"
abbr --add dstevt "docker system events"
abbr --add dstif "docker system info"
abbr --add dstpn "docker system prune"

# Abbrevations for "docker swarm"
abbr --add dsint "docker swarm init"
abbr --add dslv "docker swarm leave"
