# Abbreviations for "docker compose"
abbr --add dkcpb "docker compose text build"
abbr --add dkcpcf "docker compose config"
abbr --add dkcpcp "docker compose cp"
abbr --add dkcpce "docker compose create"
abbr --add dkcpdn "docker compose down --remove-orphans --volumes --timeout 0"
abbr --add dkcpevt "docker compose events"
abbr --add dkcpex "docker compose exec"
abbr --add dkcpimg "docker compose images"
abbr --add dkcpkl "docker compose kill"
abbr --add dkcplg "docker compose logs"
abbr --add dkcpls "docker compose ls"
abbr --add dkcppa "docker compose pause"
abbr --add dkcppr "docker compose port"
abbr --add dkcppl "docker compose pull"
abbr --add dkcpps "docker compose ps"
abbr --add dkcprs "docker compose restart"
abbr --add dkcprn "docker compose run"
abbr --add dkcpsc "docker compose scale"
abbr --add dkcpst "docker compose start"
abbr --add dkcpsp "docker compose stop"
abbr --add dkcptp "docker compose top"
abbr --add dkcpups "docker compose unpause"
abbr --add dkcpup "docker compose up"
abbr --add dkcpv "docker compose version"
abbr --add dkcpwt "docker compose wait"
abbr --add dkcpwa "docker compose watch"

# Abbrevations for "docker"
abbr --add dkca "docker container attach"
abbr --add dkccm "docker container commit"
abbr --add dkccp "docker container cp"
abbr --add dkccr "docker container create"
abbr --add dkcdf "docker container diff"
abbr --add dkcep "docker container export"
abbr --add dkcex "docker container exec"
abbr --add dkcisp "docker container inspect"
abbr --add dkckl "docker container kill"
abbr --add dkclg "docker container logs"
abbr --add dkcls "docker container ls"
abbr --add dkcpa "docker container pause"
abbr --add dkcpn "docker container prune"
abbr --add dkcpt "docker container port"
abbr --add dkcrm "docker container rm"
abbr --add dkcrn "docker container run"
abbr --add dkcrnm "docker container rename"
abbr --add dkcrs "docker container restart"
abbr --add dkcs "docker container stop"
abbr --add dkcstr "docker container start"
abbr --add dkcsts "docker container stats"
abbr --add dkct "docker container top"
abbr --add dkcud "docker container update"
abbr --add dkcup "docker container unpause"
abbr --add dkcw "docker container wait"

# Abbrevations for "docker system"
abbr --add dkstdf "docker system df"
abbr --add dkstevt "docker system events"
abbr --add dkstif "docker system info"
abbr --add dkstpn "docker system prune"

# Abbrevations for "docker swarm"
abbr --add dksint "docker swarm init"
abbr --add dkslv "docker swarm leave"
