# Abbreviations for "docker compose"
abbr --add dcpb "docker compose text build"
abbr --add dcpcf "docker compose config"
abbr --add dcpcp "docker compose cp"
abbr --add dcpce "docker compose create"
abbr --add dcpd "docker compose down --remove-orphans --volumes --timeout 0"
abbr --add dcpevt "docker compose events"
abbr --add dcpimg "docker compose images"
abbr --add dcpkl "docker compose kill"
abbr --add dcplg "docker compose logs"
abbr --add dcpls "docker compose ls"
abbr --add dcppa "docker compose pause"
abbr --add dcppr "docker compose port"
abbr --add dcppl "docker compose pull"
abbr --add dcpps "docker compose ps"
abbr --add dcprs "docker compose restart"
abbr --add dcprn "docker compose run"
abbr --add dcpsc "docker compose scale"
abbr --add dcpst "docker compose start"
abbr --add dcpsp "docker compose stop"
abbr --add dcpt "docker compose top"
abbr --add dcpups "docker compose unpause"
abbr --add dcpup "docker compose up"
abbr --add dcpv "docker compose version"
abbr --add dcpwt "docker compose wait"
abbr --add dcpwt "docker compose watch"

