---
- name: Install Pipewire Alsa
  become: true
  pacman:
    name: pipewire-alsa
    state: present
- name: Install Pipewire for Pulseaudio
  become: true
  pacman:
    name: pipewire-pulse
    state: present
- name: Enable Pipewire for Pulseaudio
  systemd_service:
    name: pipewire-pulse
    scope: user
    enabled: true
    state: started
