---
- name: Install Chromium
  become: true
  pacman:
    name: chromium
    state: latest
- name: Install Google Chrome
  kewlfft.aur.aur:
    name: google-chrome
    state: latest
- name: Install Firefox
  become: true
  pacman:
    name: firefox
    state: latest
- name: Install Opera
  become: true
  pacman:
    name: firefox
    state: latest
