---
- name: Install sudo (permissions management)
  become: true
  pacman:
    name: sudo
    state: present
- name: Create the main user
  become: true
  user:
    name: "{{ user.name }}"
    uid: "{{ user.uid }}"
    groups: "{{ user.groups }}"
    shell: "{{ user.shell }}"
- name: Update the root user informations
  become: true
  user:
    name: root
    shell: "{{ root.shell }}"
- name: Allow user as a sudoers
  become: true
  community.general.sudoers:
    commands: ALL
    name: "{{ user.name }}"
    runas: root
    state: present
    user: "{{ user.name }}"
