download_url: https://galaxy.ansible.com/download/kewlfft-aur-0.10.0.tar.gz
format_version: 1.0.0
name: aur
namespace: kewlfft
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.10.0
version_url: https://galaxy.ansible.com/api/v2/collections/kewlfft/aur/versions/0.10.0/
