---
- name: Install Network Manager (Wi-Fi & ethernet manager)
  become: true
  pacman:
    name: networkmanager
    state: latest
- name: Start Network Manager service
  become: true
  service:
    enabled: true
    name: NetworkManager
    state: started
