---
- name: Install Notification Daemon
  become: true
  pacman:
    name: notification-daemon
    state: present
- name: Setup Notification Daemon
  become: true
  synchronize:
    src: notification/notification.service
    dest: /usr/share/dbus-1/services/org.freedesktop.Notification.service
