---
- name: Install Git
  become: true
  pacman:
    name: git
    state: latest
- name: Install LazyGit (Git TUI)
  become: true
  pacman:
    name: lazygit
    state: latest
- name: Install GitHub's CLI
  become: true
  pacman:
    name: github-cli
    state: latest
- name: Copy the configuration for Git
  synchronize:
    src: .gitconfig
    dest: /$HOME/
