---
- name: Install Pipewire
  become: true
  pacman:
    name: pipewire
    state: present
- name: Install Pipewire Audio
  become: true
  pacman:
    name: pipewire-audio
    state: present
- name: Install Pulsemixer (Pulseaudio Terminal UI)
  become: true
  pacman:
    name: pulsemixer
    state: present
- name: Install Playerctl (control media playing on the device)
  become: true
  pacman:
    name: playerctl
    state: present
- name: Install Pulseaudio Systray (system tray volume control)
  become: true
  pacman:
    name: pasystray
    state: present
