return {
	"williamboman/mason-lspconfig.nvim",
	dependencies = {
		"williamboman/mason.nvim",
	},
	opts = {
		automatic_instalation = true,
		ensure_installed = {
			"angularls",
			"ansiblels",
			"bashls",
			"biome",
			"cssls",
			"cssmodules_ls",
			"denols",
			"docker_compose_language_service",
			"dockerls",
			"elmls",
			"emmet_language_server",
			"eslint",
			"gopls",
			"graphql",
			"html",
			"intelephense",
			"java_language_sever",
			"jsonls",
			"lua_ls",
			"marksman",
			"nginx_language_server",
			"prismals",
			"rust_analyzer",
			"sqlls",
			"svelte",
			"templ",
			"ts_ls",
			"vls",
			"vuels",
			"yamlls",
		},
	},
}
