---
- name: Arch with Gnome and AMD
  hosts: all
  connection: local
  vars:
    ansible_python_interpreter: auto_silent
  gather_facts: false
  roles:
    - base
    - amd
    - xorg
    - fish
    - fontconfig
    - kitty
    - felix
    - tmux
    - neovim
    - ufw
    - pipewire
    - hostname
    - timezone
    - locale
    - network
    - gnome
