---
- name: Update Archlinux cache & packages
  become: true
  pacman:
    update_cache: true
- name: Install Reflector (mirrorlist optimizer)
  become: true
  pacman:
    name: reflector
    state: latest
- name: Synchronize the Reflector configuration
  become: true
  synchronize:
    src: reflector
    dest: /etc/xdg
- name: Enable the Reflector service at boot time
  become: true
  systemd_service:
    name: reflector
    enabled: true
