---
- name: Install Xorg AMDGPU (AMD graphics driver for Xorg)
  become: true
  pacman:
    name: xf86-video-amdgpu
    state: latest
- name: Install Vulkan Radeon (Vulkan for AMDGPU)
  become: true
  pacman:
    name: vulkan-radeon
    state: latest
- name: Install Mesa (graphics driver)
  become: true
  pacman:
    name: mesa
    state: latest
- name: Install Libva Mesa (accelerated video decoding driver)
  become: true
  pacman:
    name: libva-mesa-driver
    state: latest
- name: Install Radeon Top (graphics monitoring)
  become: true
  pacman:
    name: radeontop
    state: latest
- name: Install Mesa Vdpau (accelerated video decoding driver)
  become: true
  pacman:
    name: mesa-vdpau
    state: latest
- name: Install AMD microcode
  become: true
  pacman:
    name: amd-ucode
    state: latest
